name: Build and scan action
on: [push]
jobs:
  Build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build . -t ${{ github.repository }}